# YAML is a common format for configuration because it's human-readable and can handle nested configurations easily.

# config.yaml

database:
  url: "postgresql://user:password@localhost/dbname"
  pool_size: 10

api:
  base_url: "https://api.example.com"
  timeout: 30

logging:
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(message)s"

app:
  debug: true
  version: "1.0.0"
